# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\s_aza\OneDrive\Рабочий стол\diceroller_v1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 326)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.diceCount_line = QtWidgets.QLineEdit(self.centralwidget)
        self.diceCount_line.setObjectName("diceCount_line")
        self.horizontalLayout.addWidget(self.diceCount_line)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.diceDimentional_line = QtWidgets.QLineEdit(self.centralwidget)
        self.diceDimentional_line.setObjectName("diceDimentional_line")
        self.horizontalLayout.addWidget(self.diceDimentional_line)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.diceBonus_line = QtWidgets.QLineEdit(self.centralwidget)
        self.diceBonus_line.setObjectName("diceBonus_line")
        self.horizontalLayout.addWidget(self.diceBonus_line)
        self.rollDice_button = QtWidgets.QPushButton(self.centralwidget)
        self.rollDice_button.setObjectName("rollDice_button")
        self.horizontalLayout.addWidget(self.rollDice_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.result_text = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_text.sizePolicy().hasHeightForWidth())
        self.result_text.setSizePolicy(sizePolicy)
        self.result_text.setObjectName("result_text")
        self.verticalLayout.addWidget(self.result_text)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.ip_line = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_line.setObjectName("ip_line")
        self.horizontalLayout_2.addWidget(self.ip_line)
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout_2.addWidget(self.connect_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.createServer_button = QtWidgets.QPushButton(self.centralwidget)
        self.createServer_button.setObjectName("createServer_button")
        self.verticalLayout_2.addWidget(self.createServer_button)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DiceRoller"))
        self.label_2.setText(_translate("MainWindow", "Бросок:"))
        self.label.setText(_translate("MainWindow", "d"))
        self.label_5.setText(_translate("MainWindow", "+"))
        self.rollDice_button.setText(_translate("MainWindow", "Бросить"))
        self.label_4.setText(_translate("MainWindow", "Подключение к удалённому серверу"))
        self.label_3.setText(_translate("MainWindow", "IP:"))
        self.connect_button.setText(_translate("MainWindow", "Подключиться"))
        self.createServer_button.setText(_translate("MainWindow", "Создать сервер"))
